<?php

return [
    0 => [
        'name' => 'type',
        'title' => '选择云存储类型',
        'type' => 'select',
        'content' => [
            'local' => '本地存储',
            'qiniu' => '七牛云存储',
            'qcloud' => '腾讯云存储',
            'aliyun' => '阿里云存储',
        ],
        'value' => 'qiniu',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    1 => [
        'name' => 'domain',
        'title' => '云存储域名',
        'type' => 'string',
        'content' => '',
        'value' => 'http://qgj8s2d2j.hn-bkt.clouddn.com',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    2 => [
        'name' => 'qiniu',
        'title' => '七牛云存储',
        'type' => 'array',
        'content' => [
            'accessKey' => 'xxxxxx',
            'secretKey' => 'xxxxxx',
            'bucket' => 'test-bucket-name',
            'domain' => 'xxxx.bkt.clouddn.com',
        ],
        'value' => [
            'accessKey' => 'hzEL3E4SN7KZUxzaNvK4RGusHReGmDkUm_EiUFO2',
            'secretKey' => '1Eo4iik-Tqp0GnQF0eW2kRRO_4_S44fMClKJ6KgO',
            'bucket' => 'minprogram-ns',
            'domain' => 'qgj8s2d2j.hn-bkt.clouddn.com',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    3 => [
        'name' => 'qcloud',
        'title' => '腾讯云存储',
        'type' => 'array',
        'content' => [
            'secretId' => 'xxxxxx',
            'secretKey' => 'xxxxxx',
            'bucket' => 'xxxxxx',
            'region' => 'xxxxxx',
        ],
        'value' => [
            'secretId' => 'xxxxxx',
            'secretKey' => 'xxxxxx',
            'bucket' => 'xxxxxx',
            'region' => 'xxxxxx',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    4 => [
        'name' => 'aliyun',
        'title' => '阿里云存储',
        'type' => 'array',
        'content' => [
            'accessId' => '<aliyun access id>',
            'accessSecret' => '<aliyun access secret>',
            'bucket' => '<bucket name>',
            'endpoint' => '<endpoint address>',
        ],
        'value' => [
            'accessId' => '<aliyun access id>',
            'accessSecret' => '<aliyun access secret>',
            'bucket' => '<bucket name>',
            'endpoint' => '<endpoint address>',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
